tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-bright": "#2c2c2c",
        "surface-container-highest": "#262626",
        "on-tertiary-fixed-variant": "#006832",
        "secondary-fixed-dim": "#f7ba00",
        "surface-dim": "#0e0e0e",
        "on-surface": "#ffffff",
        "tertiary-container": "#3fff8b",
        "on-tertiary-container": "#005d2c",
        "error": "#ff6e84",
        "on-primary-container": "#280072",
        "primary-fixed-dim": "#9c7eff",
        "outline-variant": "#484847",
        "tertiary": "#b5ffc2",
        "primary-container": "#a98fff",
        "on-secondary-fixed": "#443100",
        "on-surface-variant": "#adaaaa",
        "on-error-container": "#ffb2b9",
        "primary-fixed": "#a98fff",
        "outline": "#767575",
        "on-primary-fixed-variant": "#32008a",
        "on-error": "#490013",
        "surface-variant": "#262626",
        "on-background": "#ffffff",
        "surface-container-low": "#131313",
        "on-secondary-container": "#fff6ec",
        "on-primary": "#340090",
        "surface": "#0e0e0e",
        "tertiary-fixed-dim": "#24f07e",
        "secondary-container": "#785900",
        "primary-dim": "#7e51ff",
        "on-tertiary": "#006731",
        "tertiary-fixed": "#3fff8b",
        "secondary-dim": "#ecb200",
        "primary": "#b6a0ff",
        "error-container": "#a70138",
        "on-primary-fixed": "#000000",
        "tertiary-dim": "#24f07e",
        "secondary": "#fdc003",
        "surface-container": "#1a1a1a",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed": "#004820",
        "secondary-fixed": "#ffca4d",
        "surface-tint": "#b6a0ff",
        "error-dim": "#d73357",
        "inverse-primary": "#6834eb",
        "surface-container-high": "#20201f",
        "inverse-on-surface": "#565555",
        "on-secondary-fixed-variant": "#674c00",
        "background": "#0e0e0e",
        "on-secondary": "#553e00",
        "inverse-surface": "#fcf9f8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
}
